---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
data:
  BASEDOSDADOS_CONFIG: your-config-toml-in-base64
  BASEDOSDADOS_CREDENTIALS_PROD: your-credentials-json-in-base64
  BASEDOSDADOS_CREDENTIALS_STAGING: your-credentials-json-in-base64

---
apiVersion: v1
kind: Secret
metadata:
  name: vault-credentials
data:
  VAULT_ADDRESS: the-vault-address-in-base64
  VAULT_TOKEN: your-vault-token-in-base64

---
apiVersion: v1
kind: Secret
metadata:
  name: prefect-auth-toml
data:
  auth.toml: your-auth-toml-in-base64
